name: 'Install Foundry'
description: 'Installs Foundry'
runs:
  using: 'composite'
  steps:
    - name: 'Install Foundry'
      shell: bash
      run: |-
        export PATH="$PATH:$HOME/.foundry/bin"
        echo "$HOME/.foundry/bin" >> $GITHUB_PATH
        if command -v anvil; then
          echo "Anvil already installed"
          anvil --version
        else
          curl -L https://foundry.paradigm.xyz | bash
          foundryup
        fi
